=== dobrokot/uatraits/data/browser.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rules">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="branch"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="branch">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="branch"/>
                <xs:element ref="define"/>
                <xs:element ref="match"/>                
            </xs:choice>
            <xs:attribute name="name" type="xs:NCName"/>
            <xs:attribute name="type" type="branchType"/>
        </xs:complexType>
    </xs:element>    
    <xs:element name="define">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="pattern"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="value"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="match">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="pattern"/>
            </xs:sequence>
            <xs:attribute name="type" type="matchType"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="pattern">
        <xs:complexType mixed="true">
            <xs:attribute name="type" use="required" type="patternType"/>
            <xs:attribute name="value"/>
        </xs:complexType>
    </xs:element>    
    <xs:simpleType name="branchType">
        <xs:restriction base="xs:string">            
            <xs:enumeration value="default"/>
            <xs:enumeration value="common"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="matchType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="any"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patternType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="regex"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== dobrokot/uatraits/data/browser.xml
<?xml version="1.0"?>
<!DOCTYPE rules [
<!ENTITY ver1d "\d+">
<!ENTITY ver2d "\d+(?:\.\d+)?">
<!ENTITY ver3d "\d+(?:\.\d+){0,2}">
<!ENTITY ver "\d[\d\.]*">
<!ENTITY word "\w+">
]>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="browser.xsd" minver="1.1" date="2012.02.10.12.50">
	<branch name="Mobile">
		<!-- Mobile bullshit -->
		<match type="any">
			<pattern type="string">Android</pattern>
			<pattern type="string">iPhone</pattern>
			<pattern type="string">Bada/</pattern>
			<pattern type="string">iPad</pattern>
			<pattern type="string">iPod;</pattern>
			<pattern type="string">Mobile Safari</pattern>
			<pattern type="string">MobileSafari</pattern>
			<pattern type="string">Opera Mob</pattern>
			<pattern type="string">Opera Tab</pattern>
			<pattern type="string">Opera Mini</pattern>
			<pattern type="string">CLDC-</pattern>
			<pattern type="string">MIDP-</pattern>
			<pattern type="string">Series 60</pattern>
			<pattern type="string">Symbian</pattern>
			<pattern type="string">Windows Phone</pattern>
			<pattern type="string">ZuneWP7</pattern>			
			<pattern type="string">Skyfire</pattern>
			<pattern type="string">Windows CE</pattern>
			<pattern type="string">Maemo</pattern>
			<pattern type="string">Fennec</pattern>
			<pattern type="string">UCWEB</pattern>
			<pattern type="string">UC Browser</pattern>
			<pattern type="string">UP.Browser</pattern>
			<pattern type="string">NetFront</pattern>
			<pattern type="string">Obigo</pattern>
			<pattern type="string">hpwOS</pattern>
			<pattern type="string">webOS</pattern>
			<pattern type="string">BREW</pattern>
			<pattern type="string">OpenWave</pattern>
			<pattern type="string">WAP</pattern>
			<pattern type="string">Nokia</pattern>
			<pattern type="string">DoCoMo</pattern>
			<pattern type="string">Kindle</pattern>
			<pattern type="string">Minimo</pattern>
			<pattern type="string">PlayStation Portable</pattern>
			<pattern type="string">Tablet browser</pattern>
			<pattern type="string">BlackBerry</pattern>
			<pattern type="string">PlayBook</pattern>
			<pattern type="string">iTunes-i</pattern>
			<pattern type="regex">MSIE.*PPC[;)]</pattern>
			<pattern type="regex">HTC[_/]</pattern>
			<pattern type="regex">^SAMSUNG</pattern>
			<pattern type="regex">^HUAWEI</pattern>
			<pattern type="regex">^Fly</pattern>
			<pattern type="regex">^SonyEricsson</pattern>
			<pattern type="regex">^Alcatel</pattern>
			<pattern type="regex">^[\w]+ Opera/</pattern>			
		</match>
		<define name="isMobile" value="true"/>
		
		<!-- Because this motherfucker claims to be ANOTHER BROWSER --> 
		<branch name="UCBrowser">
			<match type="any">
				<pattern type="string">UC Browser</pattern>
				<pattern type="string">UCWEB</pattern>
			</match>
			<define name="BrowserEngine" value="UCBrowser"/>
			<define name="BrowserName" value="UCBrowser"/>
			<define name="BrowserVersion">
				<pattern type="regex" value="$1">UC Browser(&ver2d;)</pattern>
				<pattern type="regex" value="$1">UCWEB(&ver2d;)</pattern>
			</define>
		</branch>
		
		<branch name="Webkit">
			<match>
				<pattern type="string">WebKit</pattern>
				<pattern type="string">Mobile Safari/</pattern>				
			</match>			
			<define name="BrowserEngine" value="WebKit"/>
			<define name="BrowserEngineVersion">
				<pattern type="regex" value="$1">Web[Kk]it/(&ver;)</pattern>
			</define>
			<branch name="NokiaBrowser">
				<match type="any">
					<pattern type="string">NokiaBrowser/</pattern>
					<pattern type="string">Nokia</pattern>
					<pattern type="string">SymbianOS</pattern>
				</match>
				<define name="BrowserName" value="NokiaBrowser"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">BrowserNG/(&ver;)</pattern>
					<pattern type="regex" value="$1">Version/(&ver;)</pattern>
					<pattern type="regex" value="$1">NokiaBrowser/(&ver;)</pattern>
					<pattern type="regex" value="$1">Nokia[\w\-]*/(&ver;)</pattern>
					<pattern type="regex" value="$1">Series(?:60|80)/(&ver;)</pattern>
				</define>
			</branch>
			<branch name="Dolfin">
				<match type="any">
					<pattern type="string">Dolfin/</pattern>
				</match>
				<define name="BrowserName" value="Dolfin"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Dolfin/(&ver;)</pattern>
				</define>
			</branch>
			
			<branch name="PlayBook">
				<match type="any">
					<pattern type="string">PlayBook</pattern>
				</match>
				<define name="BrowserName" value="BlackBerry"/>				
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Version/(&ver3d;)</pattern>
				</define>
			</branch>
			
			<branch name="ChromeMobile">
				<match type="any">
					<pattern type="string">CrMo/</pattern>
				</match>
				<define name="BrowserName" value="ChromeMobile"/>				
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">CrMo/(&ver3d;)</pattern>
				</define>
			</branch>
			
			<branch name="SkyFire">
				<match>
					<pattern type="string">Skyfire/</pattern>
				</match>
				<define name="BrowserName" value="SkyFire"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Skyfire/(&ver;)</pattern>
				</define>
			</branch>
			<branch name="NetFront">
				<match>
					<pattern type="string">NetFrontLifeBrowser/</pattern>
				</match>
				<define name="BrowserName" value="NetFrontLifeBrowser"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">NetFront[\w]*/(&ver;)</pattern>
				</define>
			</branch>
			<branch name="Polaris">
				<match type="any">
					<pattern type="string">POLARIS/</pattern>
				</match>
				<define name="BrowserName" value="Polaris"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">POLARIS/(&ver;)</pattern>
				</define>
			</branch>			
			<branch name="wOSBrowser">
				<match>
					<pattern type="regex">wOSBrowser</pattern>
				</match>
				<define name="BrowserName" value="WebOSBrowser"/>
				<define name="isTouch" value="true"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">wOSBrowser/(&ver2d;)</pattern>
				</define>
				<define name="isTablet">
					<pattern type="string" value="true">TouchPad</pattern>
				</define>
			</branch>
			<branch name="Ninesky">
				<match>
					<pattern type="string">Ninesky-android-mobile/</pattern>
				</match>
				<define name="BrowserName" value="Ninesky"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Ninesky-android-mobile/(&ver;)</pattern>
				</define>
			</branch>			
			<branch name="MobileSafari">
				<match type="any">
					<pattern type="string">Mobile Safari</pattern>
					<pattern type="regex">Mobile/[\w0-9]+(?: Safari/)?</pattern>
					<pattern type="regex">Android.*Safari/</pattern>
					<pattern type="regex">Mac OS X \d[\d_]+;.*HTC[_/\s]</pattern>
				</match>
				<define name="BrowserName" value="MobileSafari"/>
				<define name="isTouch" value="true"/>
				<define name="isTablet">
					<pattern type="string" value="true">Android 3</pattern>
					<pattern type="string" value="true">iPad</pattern>
				</define>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Version/(&ver;)</pattern>
				</define>
			</branch>
			<branch type="default">
				<define name="BrowserName" value="UnknownWebkit"/>
				<define name="BrowserName">
					<pattern type="string" value="GenericSafari">Safari/</pattern>
				</define>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Version/(&ver;)</pattern>
				</define>
			</branch>
			<branch type="common">
				<define name="BrowserShell">
					<pattern type="string" value="Diigo">Diigo</pattern>
					<pattern type="string" value="Diigo">iChromy</pattern>
				</define>
			</branch>
		</branch>		
		<branch name="Presto">
			<match>
				<pattern type="string">Opera</pattern>
			</match>
			<define name="BrowserEngine" value="Presto"/>			
			<define name="BrowserEngineVersion">
				<pattern type="regex" value="$1">Presto/(&ver;)</pattern>
			</define>
			<branch name="OperaMini">
				<match>
					<pattern type="string">Opera Mini/</pattern>
				</match>
				<define name="BrowserName" value="OperaMini"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Opera Mini/(&ver2d;)</pattern>
				</define>
			</branch>
			<branch name="OperaMobile">
				<match type="any">
					<pattern type="string">Opera Mobi/</pattern>
					<pattern type="string">Opera Tablet/</pattern>
					<pattern type="regex">Opera/(&ver2d;)</pattern>
					<pattern type="regex">Opera &ver;</pattern>
				</match>
				<define name="BrowserName" value="OperaMobile"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Version/(&ver2d;)</pattern>
					<pattern type="regex" value="$1">Opera[\s/]?(&ver2d;)</pattern>
				</define>
				<define name="isTablet">
					<pattern type="string" value="true">Tablet/</pattern>
					<pattern type="string" value="true">Tablet browser</pattern>
				</define>
			</branch>
		</branch>
		<branch name="Gecko">
			<match type="any">
				<pattern type="string">Fennec</pattern>
				<pattern type="string">Firefox</pattern>
				<pattern type="string">Minimo</pattern>
			</match>
			<define name="BrowserEngine" value="Gecko"/>			
			<define name="isTouch" value="true"/>
			<define name="BrowserEngineVersion">
				<pattern type="regex" value="$1">rv:(&ver;)</pattern>
			</define>
			<branch name="Frefox">
				<match type="any">
					<pattern type="string">Firefox/</pattern>
					<pattern type="string">Fennec/</pattern>
				</match>
				<define name="BrowserName" value="MobileFirefox"/>
				<define name="BrowserVersion">
					<pattern type="regex" value="$1">Firefox/(&ver;)</pattern>
					<pattern type="regex" value="$1">Fennec/(&ver;)</pattern>
				</define>
				<define name="isTablet">
					<pattern type="string" value="true">Tablet browser</pattern>
				</define>
			</branch>
			<branch name="Minimo">
				<match type="any">
